### ISSUE TITLE
AES in CTR mode: chunks with streamEncrypt

### ISSUE THREAD

**Issue by RaymondBakker** [lt/PHP-AES#1]
Awesome project.. but I noticed something strange when using AES in CTR mode with streamEncrypt for chunk encrypting/decrypting..

The first steamEncrypt works as expected but when calling a second one with the same encryptionContext the library goes into an infinite loop.

My code:

```
	$key = new AES\Key('abcdefghijklmnop');
	$nonce = 'abcdefghijklmnop';
	
	$ctr = new AES\CTR;
	$encryptionContext = $ctr->initEncryption($key, $nonce);
	
	$plaintext0 = "Secret string part 1";
	$plaintext1 = "Secret string part 2";
	
	$ciphertext = $ctr->streamEncrypt($encryptionContext, $plaintext0);
	$ciphertext .= $ctr->streamEncrypt($encryptionContext, $plaintext1);
	
	$decryptionContext = $ctr->initDecryption($key, $nonce);
	$result = $ctr->streamDecrypt($decryptionContext, $ciphertext);
	
	var_dump($result);
```

I debugged some lines and I think it may be related to this line:

`$bytesRequired = strlen($message) - strlen($keyStream);`
(https://github.com/lt/PHP-AES/blob/master/lib/CTR.php#L43)

This will hold a negative value when the second call to streamEncrypt is made and thus cause the subsequent while loop to run forever:

`while ($blockCount--) {`

I think the solution may be to ABS the value in $bytesRequired but I don't know enough about crypto to be certain.

Help would be much appreciated. ;)

**Comment by lt** [comment]
Hey @RaymondBakker 

You're absolutely right, going negative here will cause an infinite loop.

I could swear I fixed this ages ago... possibly in a different library entirely. I'll have a quick dig around and fix it shortly.

**Comment by lt** [comment]
Looks like I fixed it in ChaCha20 - https://github.com/lt/PHP-ChaCha20/commit/8c63c2790cd0fcbb21e577a57c32387efec03c6a
